---
version: "3.8"
services:
       myjenkins:
           image: jenkins/jenkins
           ports:
              - 5050:8080
       qaserver:
           image: tomee
           ports: 
              - 5052:8080
           links:
              - myjenkins:jenkins
       prodserver:
           image: tomee
           ports:
              - 5054:8080
           links:
              - myjenkins:jenkins1
...