---
version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
  adminer:
    image: adminer
    restart: always
    ports:
      - 9092:8080
    link:
      - db:mydb
