---
version: "3.8"
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: mydb
  mywordpress:
    image: wordpress
    ports:
      - 8888:80
    links:
      - mydb:mysql
